# Generated by Django 3.0.7 on 2020-07-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée'), ('available', 'Disponible'), ('taken', 'Prise')], default='open', max_length=50)),
            ],
        ),
    ]
