# Generated by Django 3.0.7 on 2020-07-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
