# Generated by Django 2.2.14 on 2020-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0005_auto_20200730_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableconnect',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
