# Generated by Django 3.0.7 on 2020-08-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0006_auto_20200730_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
