# Generated by Django 3.0.7 on 2020-08-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0007_auto_20200803_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='tableconnect',
            name='status',
            field=models.CharField(choices=[('on', 'Active'), ('off', 'Inactive')], default='on', max_length=50),
        ),
    ]
