# Generated by Django 3.0.7 on 2020-08-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0008_auto_20200803_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableconnect',
            name='code',
        ),
        migrations.AddField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('new', 'Nouvelle'), ('delivered', 'Livrée')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='table',
            name='code',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
