# Generated by Django 3.1 on 2020-08-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0011_auto_20200816_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['-date']},
        ),
    ]
