# Generated by Django 3.1 on 2020-08-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0012_auto_20200819_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='qty',
        ),
        migrations.AddField(
            model_name='command',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
