# Generated by Django 3.1 on 2020-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0013_auto_20200819_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
