# Generated by Django 3.1 on 2020-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0015_auto_20200821_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='code',
            field=models.CharField(default='0000', max_length=5),
        ),
    ]
