# Generated by Django 3.1 on 2020-08-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0017_auto_20200821_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('new', 'Nouvelle'), ('in progress', 'en cours'), ('delivered', 'Livrée'), ('payed', 'Payée')], default='new', max_length=50),
        ),
    ]
