# Generated by Django 3.1 on 2020-08-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0019_payment_paymentmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
