# Generated by Django 3.1 on 2020-08-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0021_remove_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('cb', 'Carte bleue'), ('cash', 'liquide'), ('tr', 'Ticket restaurant')], default='cb', max_length=50),
            preserve_default=False,
        ),
    ]
