# Generated by Django 3.1 on 2020-08-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0022_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
    ]
