# Generated by Django 3.1 on 2020-08-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0023_remove_payment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
