# Generated by Django 3.1 on 2020-09-04 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_staffcall'),
        ('command', '0024_bill_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command.table')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.staffcall')),
            ],
        ),
    ]
