# Generated by Django 3.1 on 2020-09-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0025_call_callmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='Table',
            new_name='table',
        ),
    ]
