# Generated by Django 3.1 on 2020-09-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0026_auto_20200904_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('cb', 'Carte bleue'), ('cash', 'liquide'), ('tr', 'Ticket restaurant')], max_length=50, null=True),
        ),
    ]
