language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt


# safelist
branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE="MFPservices.settings"

services:
  - postgresql

addons:
  postgresql: "10.3"

script:
  - python manage.py test product/tests
  - python manage.py test message/tests
  - python manage.py test command/tests