# Generated by Django 3.0.7 on 2020-07-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200702_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producttaxe',
            name='id',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='producttaxe',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
