# Generated by Django 3.0.7 on 2020-07-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200702_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductFamily',
        ),
        migrations.DeleteModel(
            name='ProductTaxe',
        ),
    ]
