# Generated by Django 3.1 on 2020-08-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avaiable',
            field=models.BooleanField(default=True),
        ),
    ]
