# Generated by Django 3.1 on 2020-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_avaiable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCall',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
